#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.111.112.220:8848
#    alicloud:
#      access-key: NULL
#      secret-key: NULL
#      oss:
#        endpoint: NULL
#        bucket: mall-zmm
#
#  application:
#    name: mall-third-party
#server:
#  port: 13000
